export const ATOMIC_ATOM_TAGS = [
  'ad-avatar',
  'ad-badge',
  'ad-button',
  'ad-checkbox',
  'ad-divider',
  'ad-heading',
  'ad-icon',
  'ad-image',
  'ad-input-mask',
  'ad-input-number',
  'ad-input-otp',
  'ad-input-text',
  'ad-knob',
  'ad-label',
  'ad-logo',
  'ad-paragraph',
  'ad-progress-bar',
  'ad-progress-spinner',
  'ad-radio-button',
  'ad-rating',
  'ad-scroll-top',
  'ad-select-button',
  'ad-skeleton',
  'ad-slider',
  'ad-tag',
  'ad-textarea',
  'ad-tooltip',
] as const

export const ATOMIC_MOLECULE_TAGS = [
  'ad-anchor',
  'ad-float-label',
  'ad-tile',
] as const

export const ATOMIC_ORGANISM_TAGS = [
  'ad-accordion',
  'ad-auto-complete',
  'ad-card',
  'ad-chart',
  'ad-color-picker',
  'ad-data-table',
  'ad-date-picker',
  'ad-deferred-content',
  'ad-dialog',
  'ad-dock',
  'ad-file-upload',
  'ad-mega-menu',
  'ad-menu',
  'ad-meter-group',
  'ad-multi-select',
  'ad-panel',
  'ad-password',
  'ad-pick-list',
  'ad-popover',
  'ad-scroll-panel',
  'ad-select',
  'ad-speed-dial',
  'ad-swiper',
  'ad-tabs',
  'ad-terminal',
  'ad-timeline',
  'ad-toast',
  'ad-tree',
] as const
