create table if not exists public.page_builder_pages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  title varchar(160) not null,
  slug varchar(180) not null unique,
  status varchar(30) not null default 'draft',
  meta_json jsonb,
  published_version_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_builder_versions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.page_builder_pages (id) on delete cascade,
  version integer not null,
  layout_json jsonb not null,
  checksum varchar(64) not null,
  is_published boolean not null default false,
  created_by uuid references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(page_id, version)
);

alter table public.page_builder_pages
  drop constraint if exists page_builder_pages_published_version_id_fkey;

alter table public.page_builder_pages
  add constraint page_builder_pages_published_version_id_fkey
  foreign key (published_version_id)
  references public.page_builder_versions (id)
  on delete set null;

create table if not exists public.page_builder_user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  preferences jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.page_builder_pages enable row level security;
alter table public.page_builder_versions enable row level security;
alter table public.page_builder_user_preferences enable row level security;

drop policy if exists "page_builder_pages_authenticated_all" on public.page_builder_pages;
create policy "page_builder_pages_authenticated_all" on public.page_builder_pages for all to authenticated using (true) with check (true);
drop policy if exists "page_builder_versions_authenticated_all" on public.page_builder_versions;
create policy "page_builder_versions_authenticated_all" on public.page_builder_versions for all to authenticated using (true) with check (true);
drop policy if exists "page_builder_user_preferences_authenticated_all" on public.page_builder_user_preferences;
create policy "page_builder_user_preferences_authenticated_all" on public.page_builder_user_preferences for all to authenticated using (true) with check (true);
